### ISSUE TITLE
Unable to clone github repository

### ISSUE THREAD

**Issue by Rohan-Arwari** [AndreWeiner/ml-cfd-lecture#1]
I was trying to clone github repository, tried to execute this -> git clone git@github.com:AndreWeiner/ml-cfd-lecture.git
Error -> git@github.com: Permission denied (publickey).
              fatal: Could not read from remote repository.
              Please make sure you have the correct access rights and the repository exists.

**Comment by AndreWeiner** [comment]
Hi @Rohan-Arwari,

thanks for reporting this issue. The correct protocol for you is *HTTPS*, since you are not a repository owner:
```
git clone https://github.com/AndreWeiner/ml-cfd-lecture.git
```
I'll also modify the instructions in the notebook.

Best, Andre
