### ISSUE TITLE
Trouble with library file libAgentRotatingWallVelocity.so

### ISSUE THREAD

**Issue by mattsim12** [AndreWeiner/ml-cfd-lecture#10]
Hi Dr Weiner, 

Thank you so much for making your lecture material and exercises available!

I'm just having some trouble with Exercise 10/11. For some reason I’m not creating the library file libAgentRotatingWallVelocity.so and I’m not really sure how to go about fixing that.  

If you had any suggestions, I’d really appreciate them. Apologies if its something really trivial. 

Kind Regards 
Matt

**Comment by AndreWeiner** [comment]
Hi Matt,
following the steps in the [exercise notebook](https://github.com/AndreWeiner/ml-cfd-lecture/blob/main/notebooks/exercise_10_11.ipynb), could you clarify at which step the problem occurs and report potential error/warning messages? When compiling the code from within the container, you can save the output in a log file as follows:
```
wmake &> log.wmake
```
Also, you can add logs or screenshots to your message here on Github.
Cheers, Andre

**Comment by mattsim12** [comment]
Hi Andre,

I went back and did the setup exercise again, basically clean slate my system. Downloaded fresh files and everything seems to be working fine. Sorry, I must have just made a silly mistake when working through the setup. 

Thanks for your help and thanks again for the learning material, it's really great!

Cheers,

Matt
