### ISSUE TITLE
Issue with running pip3 install -r requirements.txt 

### ISSUE THREAD

**Issue by Rozie100** [AndreWeiner/ml-cfd-lecture#11]
I am receiving the following error when I run   pip3 install -r requirements.txt

Running command git clone -q git://github.com/FlowModelingControl/flowtorch.git /tmp/pip-install-0g03cni1/flowtorch
  fatal: unable to connect to github.com:
  github.c
![issue](https://user-images.githubusercontent.com/52797564/177174222-086a7309-9829-4697-9c7c-28f53141aa66.png)
om[0: 140.82.113.3]: errno=Resource temporarily unavailable

**Comment by AndreWeiner** [comment]
Hi @Rozie100,
this looks like a temporary issue. Please try the installation process again, and let me know if the issue is solved already. Alternatively, try to install flowTorch directly via pip:
```
pip3 install git+https://github.com/FlowModelingControl/flowtorch
```
Best, Andre

**Comment by Rozie100** [comment]
Thank you so much, it worked!
