### ISSUE TITLE
Singularity installation in setting up your system

### ISSUE THREAD

**Issue by abv9359** [AndreWeiner/ml-cfd-lecture#15]
Dear @AndreWeiner ,
I installed singularity 3.10.3 but encountered error in the flowpast2D cylinder. So, I went back to check if the containers are installed appropriately. But now, the singularity documentations are missing and I think the servers are not working either. While searching, I read that singularity was renamed as apptainer. So, what needs to be installed singularity or apptainer. May be the repos are getting chaged to as I can't find 3.10.3 (erased maybe).The installation guide from sylabs is not loading.
Thanks.

**Comment by AndreWeiner** [comment]
Dear @abv9359,
thanks for bringing this change to my attention. I was fully unaware of it. I will change the instructions throughout the upcoming term. Untill then, please refer to the [apptainer documentation](https://apptainer.org/docs/user/main/), and simply replace _apptainer_ with _singularity_. The interfaces sould remain compatible for the most part.
Best, Andre

**Comment by abv9359** [comment]
Dear @AndreWeiner ,
I installed apptainer, build of2016.sif and basilisk file. But while running the flow past 2D cylinder simulation, I'm encountering FOAM fatal error. Should .Allrun.singularity has to be modified in some way?
`-> FOAM FATAL ERROR: (openfoam-2106)
Cannot open file "system/decomposeParDict"

    From int main(int, char**)
    in file foamDictionary.C at line 381.

FOAM exiting

Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running renumberMesh (1 processes) on /media/abhinav/STUFF/Matlab/AI_CFD/exercises/cylinder2D with image ../../of2106.sif


--> FOAM FATAL ERROR: (openfoam-2106)
Cannot open file "system/decomposeParDict"

    From int main(int, char**)
    in file foamDictionary.C at line 381.

FOAM exiting

Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running pimpleFoam (1 processes) on /media/abhinav/STUFF/Matlab/AI_CFD/exercises/cylinder2D with image ../../of2106.sif
`

**Comment by abv9359** [comment]
I tried running the log file through  `apptainer run foamLog log.pimpleFoam`, it displays fatal error could not open image.

**Comment by JanisGeise** [comment]
Hi @abv9359,
the Allrun scripts should work, to me it looks like and issue with paths. I tried reproducing the error and noticed the following:
- when running on my main partion `/home/janis/...` the simulation works fine, when using the `of2106.sif` as well as with the `of2206-py1.12.1-cpu.sif`
- when doing the simulation on a different partion such as `/media/janis/...` I get the exact same error as you

Maybe @AndreWeiner has an idea how to fix this. Regarding the log files,  first execute `source ../../functions` from the cylinder2D case and then try to get the log files by using the command `singularityRun foamLog log.pimpleFoam`. 

Regards, Janis

**Comment by AndreWeiner** [comment]
I already observed the same behavior once before; see issue #6. This issue seems to be related to how Ubuntu mounts external devices; see also [here](https://github.com/apptainer/singularity/issues/39). Currently, I don't have a better fix than suggesting to move the execution to the main hard drive.
Best, Andre

**Comment by abv9359** [comment]
Greetings @JanisGeise @AndreWeiner ,
I shifted by directory to home, and rebuilt the files and it worked. I truly appreciate the efforts and the exact accurate identification of issues.I'm obliged.
Thanks :)

**Comment by abv9359** [comment]
Hi @AndreWeiner   @JanisGeise,
After running the simulation, I went through the coefficient.DAT file in jupyter notebook. Passed the parameters to the attributes, but can't see the coefficients of drag and lift. The range of limits is set to 2.8 and 3.3. The data frame for the coefficients also can't read them and shows NaN. Is it due to the values expressed in the form of exponents rather than integers?I'm unable to see the graph.  
![Screenshot from 2022-10-20 09-20-45](https://user-images.githubusercontent.com/95425353/196853195-20ef25f1-44aa-42db-a61d-a422f719faa2.png)

**Comment by AndreWeiner** [comment]
Have a careful look at the cell where you are reading the coefficients. Does the output of _head()_ look correct? If not, then the options passed to _read_csv()_ should be changed. Inspect the coefficient file using a text editor and consult the documentation of _read_csv()_.

Note that these exercises are created such that you learn to figure out these problems yourself, so I won't post the answer here :-)
Cheer
