### ISSUE TITLE
Error when trying to install the requirements

### ISSUE THREAD

**Issue by ErikSchulze1796** [AndreWeiner/ml-cfd-lecture#2]
Hello Andre,

unfortunately there is an error thrown when trying to install the requirements using pip3. I get the following error:

```
ERROR: Invalid requirement: 'git+git@github.com:FlowModelingControl/flowtorch.git' (from line 7 of requirements.txt)
Hint: It looks like a path. File 'git+git@github.com:FlowModelingControl/flowtorch.git' does not exist.
```

Kind regards,
Erik

**Comment by AndreWeiner** [comment]
Hi Erik,

thanks for reporting this issue. The error should be fixed already, so if you run `git pull` to update the repository, the installation should work. Let me know if this works for you.

Best, Andre
