### ISSUE TITLE
Exercise #4+5, Part I: No module named 'paraview'

### ISSUE THREAD

**Issue by lanrikhenge** [AndreWeiner/ml-cfd-lecture#25]
Hello everyone,

I am working on the exercise #4+5. I started my work with a `git pull` so everything should be up to date.
Most worked fine and I was able to execute everything including the `parameter_variation_1d.py`-file.
In the next step, I am supposed to execute a code snipped in a Jupyter notebook.
Therefore, I created a Jupyter notebook in my `excercises/`-directory. When trying to execute the notebook, I get the following error message:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [3], line 5
      3 import torch as pt
      4 import matplotlib.pyplot as plt
----> 5 from flowtorch.data import FOAMDataloader
      7 #
      8 # adjust the path if necessary
      9 #
     10 cases = glob("./boundary_layer_1D_variation/Ub_*")

File ~/Documents/master_aerospace/ml-cfd-lecture/ml-cfd/lib/python3.10/site-packages/flowtorch/data/__init__.py:7
      5 from .psp_dataloader import PSPDataloader
      6 from .tau_dataloader import TAUDataloader, TAUConfig
----> 7 from .tecplot_dataloader import TecplotDataloader
      8 from .selection_tools import mask_box, mask_sphere
      9 from .outlier_tools import iqr_outlier_replacement

File ~/Documents/master_aerospace/ml-cfd-lecture/ml-cfd/lib/python3.10/site-packages/flowtorch/data/tecplot_dataloader.py:10
      8 # third party packages
      9 import torch as pt
---> 10 from paraview import servermanager as sm
     11 from paraview.vtk.numpy_interface import dataset_adapter as dsa
     12 from paraview.simple import VisItTecplotBinaryReader

ModuleNotFoundError: No module named 'paraview'
_________________

Since the error message tells me that no module named 'paraview' is found, I checked modules of the ml-cfd environment using `>>> help('modulues')` in Python. The output does not contain paraview.

After a quick research i did not find a way to install paraview using pip.
I hope someone can help me to mitigate this problem.

Thank you,
Henrik

**Comment by JanisGeise** [comment]
Hi @lanrikhenge,

this issue has something to do with the current _flowtorch_ version (compare to issue #20). As Andre mentioned in the last lecture, the version of flowtorch currently defined in the `requirements.txt` is not correct and needs to be reinstalled as described in [lecture 4](https://andreweiner.github.io/ml-cfd-slides/ml_intro.html#/3/1), slide 4.2.

If this doesn't solve the issue, please let me know.

Regards
Janis

**Comment by lanrikhenge** [comment]
Hi @JanisGeise,

thank you for your help. I followed the instructions before trying it the first time, but it seems like I didn't do it properly, now it works!

Best regards,
Henrik
