### ISSUE TITLE
New to CFD and CNN

### ISSUE THREAD

**Issue by sayeecsm1991** [AndreWeiner/ml-cfd-lecture#32]
Hi,

I right now doing my master's in data science and engineering in India. I want to do my Master's project based on CFD and CNN. I need you to be my supervisor and guide me to carry out this project. Consider this as my respected request and please give me a positive reply.

Thanks
Sayee Chandrasekara Mouli

**Comment by AndreWeiner** [comment]
Hello Sayee,
thanks for getting in touch. Unfortunately, I can't supervise students not enrolled at my university (TU Dresden).
Best, Andre
