### ISSUE TITLE
Solution to the differential equation in the "Trends not considered in this course: Physics-informed neural networks (PINNs)" in the ml_cfd_intro 

### ISSUE THREAD

**Issue by SoufianeAitlhadj** [AndreWeiner/ml-cfd-lecture#34]
I think that the solution of the diffrential equation : 
$$
  \frac{\mathrm{d}x}{\mathrm{d}t} = -kx\quad \text{with}\quad x(t=0)=1\quad \text{and}\quad x\in\left[0, 1\right].
$$
has to be : 
$$
  x(t) = \mathrm{exp}\left(-kt\right).
$$
not 
$$
  x(t) = \mathrm{exp}\left(-kx\right).
$$
since the solution has to be a function of time t.

**Comment by AndreWeiner** [comment]
Dear @SoufianeAitlhadj,
many thanks for your comment and apologies for the delayed reply. You are correct. Good job spotting this typo. I'll note this change for the next revision.
Best, Andre
