### ISSUE TITLE
Exercise 5 no module named 'flowtorch.data'

### ISSUE THREAD

**Issue by hyzahw** [AndreWeiner/ml-cfd-lecture#37]
Hi,

In exercise 5, while trying plotting the Re numbers and after writing the line
`from flowtorch.data import FOAMDataloader`

I got the error:

> ModuleNotFoundError: No module named 'flowtorch.data'
 
I activated both python and apptainer environments before opening Jupyter via 
```
source ml-cfd/bin/activate
source ml-cfd-lecture/setup-env 
```

Any suggestions?

**Comment by AndreWeiner** [comment]
Hi @hyzahw,
it appears like flowTorch is not installed in your virtual environment. Try:
```
source ml-cfd/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
# check the pip output for warning or error messages
# run the notebook of your choice
```
Refer to [exercise 0](https://github.com/AndreWeiner/ml-cfd-lecture/blob/main/notebooks/system_setup.ipynb) for more information.
Best, Andre

**Comment by hyzahw** [comment]
Thanks @AndreWeiner, it's working fine now.
