### ISSUE TITLE
the pytorch1.12.1+cpu is unable to be installed

### ISSUE THREAD

**Issue by smallduan** [AndreWeiner/ml-cfd-lecture#38]
Hi
While I am configuring my pyhon environment, I am facing problem, it shows that pytorch doesn't contain this version of package anymore, if I can install oter version instead?
![image](https://github.com/AndreWeiner/ml-cfd-lecture/assets/52167150/dd7ed45d-015f-4f91-918b-4263b53c8841)

**Comment by smallduan** [comment]
I also try to install the torch1.12.1 cpu by myself, but it still  failed
![image](https://github.com/AndreWeiner/ml-cfd-lecture/assets/52167150/4cf656e6-8190-411e-995c-46a64a91e7d0)

![image](https://github.com/AndreWeiner/ml-cfd-lecture/assets/52167150/6884b1d5-3e1b-4f95-8f5a-837af74040e5)

**Comment by AndreWeiner** [comment]
Hi @smallduan,
thanks for reporting the issue. I assume you are working with a fairly recent OS version, e.g., Ubuntu 24.04?
Switching to a newer version of the PyTorch Python package will introduce a version conflict with the C++ frontend (libTorch). So, to run drlFoam with a newer version of PyTorch you need to:

1. edit the *requirements.txt* file in the drlFoam folder and set the version to the latest available version (or leave out the version specification)
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```
2. install the new packages in the virtual environment
2. remove the *libtorch* folder within *drlFoam*
3. edit the [setup-env](https://github.com/OFDataCommittee/drlfoam/blob/main/setup-env) in the *drlFoam* folder and switch to the latest version of libTorch (**2.3.1**):
```
    if [ ! -d $DRL_TORCH ];
    then
        echo "Could not find libTorch dependencies. Downloading libTorch to ${DRL_TORCH}"
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip && \
        unzip libtorch-cxx11-abi-shared-with-deps-2.3.1+cpu.zip
        rm libtorch-cxx11-abi-shared-with-deps-2.3.1+cpu.zip
    fi
```
4. run *Allwmake* to check if the code compiles with the latest version (not tested)

Please let me know if this works for you.
Best, Andre

**Comment by smallduan** [comment]
Hi 
Thank you, It works for me.
