### ISSUE TITLE
Review exercise 0 & 1

### ISSUE THREAD

**Issue by JanisGeise** [AndreWeiner/ml-cfd-lecture#39]
Hi @AndreWeiner ,

I reviewed exercise 0 & 1 and found some issues / have some suggestions:

- In exercise 0, cell 22: we need to re-assign the dict, since it gets overwritten in cell 19 with an iterator:
```
# re-assign dict
labels_and_units["x"] = "m"
labels_and_units["U"] = "m/s"

for key in labels_and_units.keys():
...
```

Regarding exercise 1:

regarding WSL:
- when executing the setup on WSL you can check if WSL 2 is used (**before** installing Ubuntu) by opening a Powershell and executing `wsl -l -v`
- if it displays version 1, change the version to WSL 2 by executing `wsl --set-default-version 2` (also in a Powershell)
- after installing Ubuntu and starting it for the first time, it may display an error message that a Kernel needs to be installed as described in the [Microsoft documentation](https://learn.microsoft.com/de-de/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package). Once the Kernel is installed, the setup should work without any issues

regarding Python:
- before compiling Python, `sqlite3` needs to be installed first (at least on my system with Ubuntu 20.3), otherwise this will lead to an `ImportError: No module named _sqlite3` when trying to execute `jupyter-lab` 
- to install `squlite3` execute `sudo apt-get install libsqlite3-dev` **before** compiling Python
- maybe mention to adjust `make -j 8` based on the number of CPU's available when compiling Python
- the command `make altinstall` has to be executed with `sudo` as `sudo make altinstall`
- before continuing with creating the venv, we have to go back to the top-level of the repository by executing `cd ..`, since we are still in the Python directory

other:
- maybe mention that the setup (venv and containers) require approx. 8 GB of disk space
- maybe mention that Python as well as the lolcow container can be removed after installing everything
- maybe mention to deactivate the venv before compiling Apptainer
- there is a typo in the section jupyter labs in the 2. comment (`and` instead of `at`)

Regards,
Janis

**Comment by AndreWeiner** [comment]
Thanks, really helpful! All remarks are addressed in the commits above, so I close this issue for now. Feel free to re-open it if more stuff pops up.
Best, Andre

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,

The setup for WSL changed a little bit when running on Windows 11. After installing WSL, the error `Error: 0x8007019e The Windows Subsystem for Linux has not been enabled.` is displayed. This can be resolved by executing the steps described [here](https://medium.com/@osaswijojames/resolving-error-0x8007019e-the-windows-subsystem-for-linux-has-not-been-enabled-4cdac4708b17):
1. search for `Turn Windows features on or off`
2. tick the checkbox for `Windows Subsystem for Linux` and `Virtual Machine Platform`
3. open up a PowerShell and execute `wsl --update`

If the checkbox `Virtual Machine Platform` is not activated, this will yield a `Error: 0x80370114 The operation could not be started because a required feature is not installed.`as described [here](https://learn.microsoft.com/en-us/answers/questions/1187339/resolving-error-0x80370114-the-operation-could-not).

Maybe it is also helpful to mention that if you encounter an error when running the `make` command during the installation of `Apptainer` this usually means that the installation of `Go` went wrong. A complete removal and clean installation of `Go` should fix the issue.

Another common issue is an error `Package python3.12-venv is not available, but is referred to by another package.` when executing `sudo apt install python3.12-venv`. In this case, executing `sudo apt update` followed by `sudo apt upgrade` should fix the issue.

Regards,
Janis
