### ISSUE TITLE
Error running pimplefoam

### ISSUE THREAD

**Issue by Akashdl** [AndreWeiner/ml-cfd-lecture#6]
`./Allrun.singularity`
Running blockMesh on .../ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif
Running setExprBoundaryFields on .../ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif
Running decomposePar on .../ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running renumberMesh (1 processes) on  .../ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'

I get this error message in log.blockMesh, log.decomposePar and log.setExprBoundaryFields 

```
--> FOAM FATAL ERROR: (openfoam-2106)
cannot find file "/home/akash/system/controlDict"

    From virtual Foam::autoPtr<Foam::ISstream> Foam::fileOperations::uncollatedFileOperation::readStream(Foam::regIOobject&, const Foam::fileName&, const Foam::word&, bool) const
    in file global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C at line 542.

FOAM exiting
```

**Comment by AndreWeiner** [comment]
Dear @Akashdl,
thanks for reporting this issue. What environment are you using, WSL or a native installation? From the error messages, it appears like the *Allrun.singularity* script is not executed in the right folder. The output should look something like this:
```
Running blockMesh on /home/akash/ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif
```
Best, Andre

**Comment by Akashdl** [comment]
I am using native Ubuntu 20.04.
I am running the script Allrun.singularity from 

`akash@akash:/media/akash/Data/Akash_D_L/TU_Braunschweig/3_Sem/Machine-learning-in-computational-fluid-dynamics/ml-cfd-lecture/exercises/cylinder2D$ ./Allrun.singularity`

and the message in terminal is 
`Running blockMesh on /media/akash/Data/Akash_D_L/TU_Braunschweig/3_Sem/Machine-learning-in-computational-fluid-dynamics/ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif`
`Running setExprBoundaryFields on /media/akash/Data/Akash_D_L/TU_Braunschweig/3_Sem/Machine-learning-in-computational-fluid-dynamics/ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif`
`Running decomposePar on /media/akash/Data/Akash_D_L/TU_Braunschweig/3_Sem/Machine-learning-in-computational-fluid-dynamics/ml-cfd-lecture/exercises/cylinder2D with image ../../of2106.sif`
`Error getting 'numberOfSubdomains' from 'system/decomposeParDict'`

and the error message in the log files are the same

Best,
Akash

**Comment by AndreWeiner** [comment]
I see. The issue is probably related to mounting the external hard drive into the container. Does it work if you move the *ml-cfd-lecture* folder to your home directory?

**Comment by Akashdl** [comment]
I made a fresh clone in home directory and setup requirements as said in exercise-1 .
`Error getting 'numberOfSubdomains' from 'system/decomposeParDict'`
Still it has errors I am attaching the log files
[blockMesh.log](https://github.com/AndreWeiner/ml-cfd-lecture/files/7491058/blockMesh.log)
[decomposePar.log](https://github.com/AndreWeiner/ml-cfd-lecture/files/7491059/decomposePar.log)
[pimpleFoam.log](https://github.com/AndreWeiner/ml-cfd-lecture/files/7491060/pimpleFoam.log)
[renumberMesh.log](https://github.com/AndreWeiner/ml-cfd-lecture/files/7491061/renumberMesh.log)
[setExprBoundaryFields.log](https://github.com/AndreWeiner/ml-cfd-lecture/files/7491062/setExprBoundaryFields.log)
.

**Comment by AndreWeiner** [comment]
Ok, the mounting issue seems to be gone. The second issue is was related to the function to fetch the number of processors. I corrected the function, so running `git pull` and then trying the instructions again should make it work.
Best, Andre
