### ISSUE TITLE
Typos in the lecture slide

### ISSUE THREAD

**Issue by JihooKang-KOR** [AndreWeiner/ml-cfd-lecture#8]
Dear Andre,

I guess there are some typos in the third lecture slide as follows:
1. In the page 9.22, y+ is mentioned as y\*nu/u_tau, but I believe that y+ = y\*u_tau/nu would be correct. (In the lecture notebook, the expression is also the same.)
2. In the same page, the part -u+\*kappa\*(1 + u+\*kappa)/2 would be -u+\*kappa\*(1 + u+\*kappa/2). (But the equation is correctly expressed in the notebook.)
3. In the page 9.23, x and y-axis should be reversed. (x-axis : y+ and y-axis : u+)

I found them when I was dealing with Spalding's function.

It would be great if you could check the above.

Best regards,
Jihoo Kang

**Comment by AndreWeiner** [comment]
Hi Jihoo,
you are correct in all three points. I have revised the slides and the notebook accordingly, as you can see in the linked commit.
Thanks for your help, awesome!
Andre
