### ISSUE TITLE
Hello,Mr AndreWeiner 

### ISSUE THREAD

**Issue by chenguanxi22** [AndreWeiner/ml-cfd-lecture#9]
Sorry to disturb you, I am showing paraview: cannot connect to X server when I execute the paraview post.foma of exercise two. The school server is used. Paraview is installed on Windows 10. I look forward to your answer.

**Comment by AndreWeiner** [comment]
Dear @chenguanxi22,
it appears like you're running ParaView on a server without a graphical user interface. If you logged in via the command line (something like `ssh yourname@workstation`), try using the *-X* option to enable the X-server protocol.
In case you are using Windows Subsystem for Linux (WSL), try opening ParaView on Windows and not in the WSL. You should be able to access the WSL data from Windows.
Best, Andre

**Comment by chenguanxi22** [comment]
Dear&nbsp;Andre,
First of all, thank you for your reply, and I’m sorry to bother you again. My school’s server does not support visualization, so I downloaded Ubuntu20.04, but an error occurred when paraview post.foam, I guess it’s because of the location of of2016.sif It’s in /usr/local, so I don’t know much about Make sure you are at the top-level of the lecture repository before you run the command. Which layer does this mean to run this command?
Best, Liuhuan




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AndreWeiner/ml-cfd-lecture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 凌晨0:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AndreWeiner/ml-cfd-lecture] Hello,Mr AndreWeiner  (Issue #9)





 
Dear @chenguanxi22,
 it appears like you're running ParaView on a server without a graphical user interface. If you logged in via the command line (something like ssh ***@***.***), try using the -X option to enable the X-server protocol.
 In case you are using Windows Subsystem for Linux (WSL), try opening ParaView on Windows and not in the WSL. You should be able to access the WSL data from Windows.
 Best, Andre
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AndreWeiner** [comment]
ParaView is not installed in the container (the *sif* file). Assuming that you have a local installation of Ubuntu 20.04 (on your PC/laptop),

1. install ParaView: `sudo apt install paraview`
2. navigate to the OpenFOAM simulation folder
3. open the case `paraview post.foam`

Best, Andre

**Comment by chenguanxi22** [comment]
Thank you very much for your quick reply, and I am very sorry, because it is my first contact with this aspect, so I don’t understand a lot. Do you mean to download paraview to the container (the sif file)? But I made an error in ./Allrun.singularity. Please see the&nbsp; picture for the specific error. How can I solve it?Do I follow the three points in your reply?
Best Liu





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "AndreWeiner/ml-cfd-lecture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 晚上6:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AndreWeiner/ml-cfd-lecture] Hello,Mr AndreWeiner  (Issue #9)





 
ParaView is not installed in the container (the sif file). Assuming that you have a local installation of Ubuntu 20.04 (on your PC/laptop),
  
install ParaView: sudo apt install paraview
 
navigate to the OpenFOAM simulation folder
 
open the case paraview post.foam
  
Best, Andre
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AndreWeiner** [comment]
Ca you please provide some more details on your configuration? What operating system are you using?
Best, Andre

**Comment by chenguanxi22** [comment]
Dear AndreWeiner:
Hello, I’m sorry to bother you. I’m using Ubuntu 20.04, another system I installed on my computer. The other configurations are configured according to the configuration of your exercise 1. It has been successfully configured, but there is one point that I didn’t understand, please see the picture below, where I executed this command, I executed it in /Usr/local, and then I reported an error when I executed ./Allrun.singularity, the error was that there was not have of2106.sif, so I put of2016 .sif was copied to ml-cfd-letcure and re-executed ./Allrun.singularity, and then reported the error shown in the photo just given to you, so maybe there is a problem here?
Best Liu




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AndreWeiner/ml-cfd-lecture"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AndreWeiner/ml-cfd-lecture] Hello,Mr AndreWeiner  (Issue #9)





 
Ca you please provide some more details on your configuration? What operating system are you using?
 Best, Andre
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AndreWeiner** [comment]
I don't see any screenshot/figure. Can you post it directly on Github?

**Comment by IT-five** [comment]
When I bulid the OpenFoAM-PyTorch container, you said Make sure you are at the top-level of the lecture repository before I run the command. But I run the command in the /usr/local path, and build the Basilisk container It is also in the /usr.local path, so I put of2106.sif cp to the ml-cfd-lecture folder, and finally I execute the ./Allrun.singularity command under the exercises/cylinder2D/ path, but it appears as shown in the picture Wrong, I put down the picture link as follows, please check it out, please advise me how to do it now, thank you
The picture link :
https://stshoueducn-my.sharepoint.com/:i:/g/personal/m210911561_st_shou_edu_cn/EaEUOavh_mJGuPjv2nP_6HgBuH_O0rRSoikSUqjUnH8Zng
Best Liu

**Comment by AndreWeiner** [comment]
I see. Is it possible that you cloned the repository already some time ago (more than a couple of weeks ago)? In that case, update the repository via `git pull`. Does the *decomposeParDict* file exist in the *system* folder?

Edit: it might be a general problem that you have non-ASCII symbols in your path to the lecture folder (I guess they are Chiese symbols). You should avoid that because it can easily create trouble.

**Comment by chenguanxi22** [comment]
There is indeed a decomposeParDict file in the system folder, how can I avoid the problem that I have non-ASCII symbols in my path to the lecture folder, please give specific steps, thank you very much, I wish you all the best

**Comment by chenguanxi22** [comment]
I have changed the path to English, but an error occurred when I re-executed the ./Allrun command, because I executed it once, so there was a log file, and when I deleted it, it showed insufficient permissions. After I gave the folder chmod 777 permissions, it still can’t Delete, how can I solve it?
picture link:
https://stshoueducn-my.sharepoint.com/:i:/g/personal/m210911561_st_shou_edu_cn/EWf6eQpmfT1FoxiTtHukdKcByZTKTaqzlbw9z_KXY7er0A?e=dBldg6
Thank you very much ,Wish you all the best

**Comment by AndreWeiner** [comment]
Apparently, you do not have the right permissions to delete/read/write files. You can run everything as root (not recommended) or change the permissions. Did you use the recursive flag?
`chmod -R 777 cylinder2D`
Best, Andre

**Comment by chenguanxi22** [comment]
After your careful guidance, I successfully ran this project. Thank you very much. I am in Shanghai, China, you can come and visit if you have the opportunity, I will thank you in person！Last,Wish you all the best!
Best, Liu

**Comment by chenguanxi22** [comment]
Sorry to bother you again, I have encountered two more problems:
1. Error when using read_csv()
2. When Singularity> cd exercises/basilisk_solver/, there is no basilisk_solver file, so I created one myself, and then I executed Singularity> make &> log.make, but an error occurred in cat log.make
I have put the photo of the problem below
Best,Liu
https://stshoueducn-my.sharepoint.com/:f:/g/personal/m210911561_st_shou_edu_cn/EulgAERGZR5PtnyBsK30YwABTCEjfzjucf9k6DSj94k9BQ?e=1ZAldx

**Comment by AndreWeiner** [comment]
1) the idea of this exercise is that you learn to read the documentation linked in the exercise; there are two numbers you have to plug in, and you simply set them to zero
2) you need to make a copy of the folder located in the *test_cases* folder: `cp -r test_cases/basilisk_solver/ exercises/`

Best, Andre

**Comment by chenguanxi22** [comment]
Thank you very much!
Best,Liu

**Comment by chenguanxi22** [comment]
sorry to disturb you,I want to open the entire set of snapshots,need toclick on File->Open->bubble_..pvtu,but i can not find it in paraview,so that i can't click apply,please see the picture.
https://stshoueducn-my.sharepoint.com/:i:/g/personal/m210911561_st_shou_edu_cn/EcrX1udirZJAp9mrqAWEJbIBPO55D9OOP-aGrjOeX4DgFQ?e=iKBAFP
Best,Liu

**Comment by AndreWeiner** [comment]
Please read the instructions more carefully. Your screenshot shows that you haven't followed the exercise.
Best, Andre

**Comment by IT-five** [comment]
Thank you very much for your careful guidance,There is last one  question I need to ask you. I encountered a very difficult problem. I spent half a day not solving it, because I used VTK7, and there have been major changes in VTK, which caused my program to report an error:'vtkmodules .vtkCommonDataModel.vtkImageData' object has no attribute'Update',the program source code is as follows:
# read file for geometry
reader = vtk.vtkXMLMultiBlockDataReader()
reader.SetFileName(geometry_file)
reader.Update()
data = reader.GetOutput()
data_iterator = data.NewIterator()
img_data = data_iterator.GetCurrentDataObject()
# Calling Update() on this line is an error
img_data.Update()
point_data = img_data.GetPointData()
array_data = point_data.GetArray(0)
np_array = vtk_to_numpy(array_data)
img_shape = img_data.GetWholeExtent()
np_shape = [img_shape[3]-img_shape[2] + 1, img_shape[1]-img_shape[0] + 1, 1]
geometry_array = np_array.reshape(np_shape)
